name: rocketchat-custom
services:
  node:
    type: node:14
    globals:
      yarn: 'latest'
    build:
      - npm install -g meteor
    overrides:
      environment:
        ROOT_URL: http://rocketchat.lndo.site:3000
        MONGO_URL: mongodb://database:27017/rocketchat
        PORT: 3000

  mongo:
    type: mongo:4.4
    portforward: true

proxy:
  node:
    - rocketchat.lndo.site:3000

tooling:
  meteor:
    service: node
    cmd: /home/node/.meteor/meteor
